name: testing-env
on:
  push:
    branches:
    - develop
    - main
    
env: 
  VEG: ${{ vars.VAR1 }} 
  
jobs:
  PrintEnv:
    name: Job for ${{ vars.VAR1 }}
    runs-on: ubuntu-latest
    steps:
    - run: echo $VEG
