name: testing-env-workflow-dispatch
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which env to select
        options: 
        - ee-prime
        - ee-prod
    
env: 
  VEG: ${{ vars.VAR1 }} 
  
jobs:
  
  WhichEnv:
    name: Identify the env for job
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.env_name }}
    
    steps:
    - id: step1
      run: |
        echo "Running on branch ${{ github.ref }}"
        if [ "${{ github.event_name }}" == "workflow_dispatch"] && [ "${{ github.event.inputs.name }}" == "ee-prime" ]; then
          echo "env_name=prime" >> "$GITHUB_OUTPUT"
        elif [ "${{ github.event_name }}" == "workflow_dispatch"] && [ "${{ github.event.inputs.name }}" == "ee-prod" ]; then
          echo "env_name=prod" >> "$GITHUB_OUTPUT"
        fi  
  
  PrintEnv:
    name: Print Env according to branch - veg ${{ vars.VEG }}
    runs-on: ubuntu-latest
    needs: WhichEnv
    environment: 
      name: ${{needs.WhichEnv.outputs.output1}}
    steps:
    - run: echo $VEG hello ${{ secrets.RECIPE }} ${{needs.WhichEnv.outputs.output1}}
      env: 
        VEG: ${{ env.VEG }}
    
      
